import sys
import os
import json
import subprocess
from pipeline import stage_remove_silence

def extract_audio(video_path, out_audio):
    cmd = [
        "ffmpeg", "-y", "-i", video_path,
        "-vn", "-acodec", "pcm_s16le", "-ar", "16000", "-ac", "1",
        out_audio
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

def generate_srt(video_path, options):
    import urllib.request
    import urllib.error
    from dotenv import load_dotenv
    
    print("\n[🎬] Extracting Audio for Deepgram...")
    base_dir = os.path.dirname(os.path.abspath(video_path))
    temp_audio = os.path.join(base_dir, "_temp_whisper_audio.wav")
    extract_audio(video_path, temp_audio)

    print("\n[🤖] Booting Deepgram Nova-2 (Perfect Word Sync)...")
    try:
        load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))
        dg_api_key = os.environ.get("DEEP_GRAM")
        
        if not dg_api_key:
            raise Exception("DEEP_GRAM key not found in .env! Cannot use Deepgram.")

        print("[⚙️] Transcribing audio instantly via Deepgram API...")
        
        url = "https://api.deepgram.com/v1/listen?model=nova-2&smart_format=true&punctuate=true"
        
        with open(temp_audio, "rb") as f:
            audio_data = f.read()
            
        req = urllib.request.Request(url, data=audio_data, method="POST")
        req.add_header("Authorization", f"Token {dg_api_key}")
        req.add_header("Content-Type", "audio/wav")
        
        with urllib.request.urlopen(req) as response:
            res_data = response.read()
            dg_json = json.loads(res_data)
            
        segments = []
        words = dg_json.get("results", {}).get("channels", [{}])[0].get("alternatives", [{}])[0].get("words", [])
        
        for w in words:
            word_text = w.get("punctuated_word", w.get("word", "")).strip()
            if word_text:
                segments.append({
                    "start": w["start"],
                    "end":   w["end"],
                    "phrase": word_text
                })
        
        if os.path.exists(temp_audio):
            os.remove(temp_audio)

        print(f"\n[✅] Transcription Complete! Found {len(segments)} words.")
        print("__JSON_START__")
        print(json.dumps({
            "chopped_video": video_path,
            "segments": segments
        }))
        print("__JSON_END__")
        
    except urllib.error.HTTPError as e:
        print(f"[❌] Deepgram API failed ({e.code}): {e.read().decode()}")
    except Exception as e:
        print(f"[❌] Deepgram failed: {e}")
        import traceback
        traceback.print_exc()

def fix_with_groq(options):
    raw_segments = options.get("rawSegments", [])
    perfect_script = options.get("perfectScript", "")
    
    from dotenv import load_dotenv
    load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))
    
    groq_api_key = os.environ.get("GROQ_API_KEY")
    if not groq_api_key:
        print("[❌] GROQ_API_KEY not found in .env")
        return
        
    print("\n[🤖] Booting Groq LLM to correct spelling...")
    from groq import Groq
    client = Groq(api_key=groq_api_key)
    
    prompt = f"""You are a precise video captioning assistant.
I have a raw SRT-style JSON array generated by Whisper, which contains spelling errors.
I also have the perfect script of what was actually said.

PERFECT SCRIPT:
{perfect_script}

RAW WHISPER JSON:
{json.dumps(raw_segments)}

CRITICAL RULES:
1. Fix the spelling of the phrases in the JSON to perfectly match the PERFECT SCRIPT.
2. DO NOT change the "start" or "end" timestamps. Keep them exactly as they are.
3. You MUST output the EXACT SAME NUMBER of objects as the RAW WHISPER JSON ({len(raw_segments)} items). Do NOT add extra segments at the end. Do NOT invent new timestamps.
4. EXTREMELY IMPORTANT: The PERFECT SCRIPT contains pipe symbols ("|") which indicate scene cuts. YOU ABSOLUTELY MUST include these "|" characters at the exact same locations in your JSON output! Do NOT delete the "|" characters! If a phrase ends with a pipe in the script, it MUST end with a pipe in your JSON!
5. Output MUST be ONLY a raw JSON array of objects with "start", "end", and "phrase". NO markdown formatting. No conversational text. Just the JSON array.
"""
    try:
        response = client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model="llama-3.3-70b-versatile",
            temperature=0.1
        )
        corrected_json_str = response.choices[0].message.content.strip()
        if corrected_json_str.startswith("```json"):
            corrected_json_str = corrected_json_str.replace("```json", "").replace("```", "").strip()
            
        print("\n[✅] Groq Correction Complete!")
        print("__JSON_START__")
        print(corrected_json_str)
        print("__JSON_END__")
    except Exception as e:
        print(f"[❌] Groq failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit(1)
        
    video_path_arg = sys.argv[1]
    options_json_arg = sys.argv[2]
    options = json.loads(options_json_arg)
    
    action = options.get("transcribeAction", "transcribe")
    if action == "transcribe":
        generate_srt(video_path_arg, options)
    elif action == "groq_fix":
        fix_with_groq(options)
